### PR TITLE
Fix Discover Card 403 by manually ordering HTTP headers

### PR DESCRIPTION
**Pull request by fanqiuwen**
Since mid February Discover Card has been giving 403 Permission Denied for OFX requests that previously worked. It was [discovered on OFX Home Forum](http://www.ofxhome.com/ofxforum/viewtopic.php?pid=108449#p108449) that Discover now requires a particular set of HTTP headers ordered in a particular way. This PR implements the fix.

### CODE REVIEW

**Comment by jantman** [comment]
I can confirm that this fix works for me, though I'm still hitting #15 unless I add a ``sleep`` to ``cli.py``.

**Comment by albaguirre** [comment]
Umm this didn't work for me. Still getting 403s.

**Comment by fanqiuwen** [comment]
@albaguirre The fix is still working for me.

I'm using ofxclient as a Python library, not a cli tool. For reference, here's a minimal version of my script that downloads Discover transactions successfully, given the changes in this PR.

```
from ofxclient import Institution, CreditCardAccount
discover_args = {
    'id': '7101',
    'org': 'Discover Financial Services',
    'url': 'https://ofx.discovercard.com',
    'username': 'SECRET',
    'password': 'SECRET',
    'client_args': {
        'app_id': 'QWIN',
        'app_version': '2200',
        'ofx_version': '102'
        }
    }
discover = CreditCardAccount(institution=Institution(**discover_args),
                             number='SECRET')
for tran in discover.transactions():
    print(tran.payee, tran.amount)
```

If this works for you and the cli doesn't, then it would be a separate issue.

**Comment by albaguirre** [comment]
@fanqiuwen Huh that snippet does indeed work. But CLI doesn't ... interesting.

**Comment by jantman** [comment]
Cool, thank you so much for merging! Any chance we could get a release uploaded to PyPI?

**Comment by captin411** [comment]
Sure I'll get one out this afternoon.

David Bartle
Mobile: 805-345-6786

**Pull request merged**
